/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Data;

import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author hikigaya
 */
public class Data_siswa extends javax.swing.JFrame {
private final Connection conn = koneksi.connect();
     private DefaultTableModel tabmode;
    /**
     * Creates new form Data_siswa
     */
    public Data_siswa() {
        initComponents();
        tabelsiswa();
        refresh();
        lebarkolong();
    }
    
private void lebarkolong(){
  TableColumn lebarkolong;
        
        tabel.setAutoResizeMode(tabel.AUTO_RESIZE_OFF);
        
        lebarkolong = tabel.getColumnModel().getColumn(0);
        lebarkolong.setPreferredWidth(140);
        lebarkolong = tabel.getColumnModel().getColumn(1);
        lebarkolong.setPreferredWidth(300);
        lebarkolong = tabel.getColumnModel().getColumn(2);
        lebarkolong.setPreferredWidth(400);
        lebarkolong = tabel.getColumnModel().getColumn(3);
        lebarkolong.setPreferredWidth(200);
        lebarkolong = tabel.getColumnModel().getColumn(4);
        lebarkolong.setPreferredWidth(100);
         lebarkolong = tabel.getColumnModel().getColumn(5);
        lebarkolong.setPreferredWidth(100);

}    
   private void refresh() {
        txtnis.setText("");
        txtnama.setText("");
        txtalamat.setText("");
        txtnohp.setText("");
        jekel.setSelectedItem(null);
        
       
        kelas.setSelectedItem(null);
        }   
    
  protected void tabelsiswa(){
        Object[] Baris ={"NIS","NAMA"," ALAMAT"," NO HP","JENIS KELAMIN","KELAS"};
        tabmode = new DefaultTableModel(null, Baris);
        tabel.setModel(tabmode);
        String sql = "select * from siswa order by nis asc";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String data1 = hasil.getString("nis");
                String data2 = hasil.getString("nama");
                String data3 = hasil.getString("alamat");
                String data4 = hasil.getString("no_hp");
                String data5 = hasil.getString("jenis_kelamin");
                String data6 = hasil.getString("kelas");
                
                String[] data={data1,data2,data3,data4,data5,data6,};
                tabmode.addRow(data);
            }
        }      
        
        catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnis = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtnohp = new javax.swing.JTextField();
        jekel = new javax.swing.JComboBox<>();
        kelas = new javax.swing.JComboBox<>();
        btnsave = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbaru = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        tcari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtnis, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 270, 40));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 270, 40));
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 270, 40));

        txtnohp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnohpKeyPressed(evt);
            }
        });
        getContentPane().add(txtnohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 270, 40));

        jekel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        getContentPane().add(jekel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 140, 40));

        kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10", "11", "12", " " }));
        getContentPane().add(kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 140, 40));

        btnsave.setText("Simpan");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 180, 40));

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 180, 40));

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 180, 40));

        btnbaru.setText("Baru");
        btnbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbaruActionPerformed(evt);
            }
        });
        getContentPane().add(btnbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 180, 40));

        btncetak.setText("Print");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });
        getContentPane().add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 180, 40));

        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcariKeyReleased(evt);
            }
        });
        getContentPane().add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 410, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("NIS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("NAMA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("ALAMAT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("NO HANDPHONE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("JENIS KELAMIN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("KELAS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jButton1.setText("Cari");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, -1, 30));

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 150, 40));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jScrollPane2.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1210, 240));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMousePressed
 int bar = tabel.getSelectedRow();
        
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        
       
        txtnis.setText(a);
        txtnama.setText(b);
         txtalamat.setText(c);
        
        txtnohp.setText(d);
        
        jekel.setSelectedItem(e);
        kelas.setSelectedItem(f);           // TODO add your handling code here:
    }//GEN-LAST:event_tabelMousePressed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
 {
          
            String sql = "insert into siswa values(?,?,?,?,?,?)";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, txtnis.getText());
                stat.setString(2, txtnama.getText());
                stat.setString(3, txtalamat.getText());
                stat.setString(4, txtnohp.getText());
                stat.setString(5, (String) jekel.getSelectedItem());
                stat.setString(6, (String) kelas.getSelectedItem());
               
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
               
                txtnis.requestFocus();
              
            }   
            
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+ex);
            } 
            tabelsiswa();
            refresh();
            lebarkolong();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
   int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin mengubah data?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if(ok==0){
           
            String sql = "update siswa set nis=?,"
                    + "nama=?,"
                    + "alamat=?,"
                    + "no_hp=?,"
                    + "jenis_kelamin=?,"
                   
                    + "kelas=? "
                    + "where nis='"+txtnis.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, txtnis.getText());
                stat.setString(2, txtnama.getText());
                stat.setString(3, txtalamat.getText());
                stat.setString(4, txtnohp.getText());
                stat.setString(5, (String) jekel.getSelectedItem());
                stat.setString(6, (String) kelas.getSelectedItem());
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                refresh();
                txtnis.requestFocus();
                tabelsiswa();
            }  
            
            catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
            } 
        }           // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
 {
            String sql = "delete from siswa where nis='"+txtnis.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                refresh();
                txtnis.requestFocus();
                tabelsiswa();
            }   
            
            catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus "+e);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbaruActionPerformed
refresh();        // TODO add your handling code here:
    }//GEN-LAST:event_btnbaruActionPerformed

    private void tcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyReleased
 tabmode.getDataVector().removeAllElements();
        tabmode.fireTableDataChanged();

        try {
            Connection connection = koneksi.connect();
            Statement statement = connection.createStatement();

            String sql = "select * from siswa where nis like '%" 
                    + tcari.getText() + "%' or nis like'%" 
                    + tcari.getText() + "%' or nama like'" 
                    + tcari.getText() + "%' or alamat like'%" 
                    + tcari.getText() + "%' or no_hp like'%" 
                    + tcari.getText() + "%' or jenis_kelamin like'%" 
                    + tcari.getText() + "%' " + "or kelas like'%" 
                    + tcari.getText() + "%'";
            ResultSet resulSet = statement.executeQuery(sql);

            while (resulSet.next()) {
                Object[] o = new Object[6];
                o[0] = resulSet.getString("nis");
                o[1] = resulSet.getString("nama");
                 o[2] = resulSet.getString("alamat");
                o[3] = resulSet.getString("no_hp");
                o[4] = resulSet.getString("jenis_kelamin");
                o[5] = resulSet.getString("kelas");
              
                
                tabmode.addRow(o);
            }
            resulSet.close();
            statement.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }            // TODO add your handling code here:
    }//GEN-LAST:event_tcariKeyReleased

    private void txtnohpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnohpKeyPressed
 if (evt.getKeyCode()== KeyEvent.VK_ENTER){
          
            String sql = "insert into siswa values(?,?,?,?,?,?)";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, txtnis.getText());
                stat.setString(2, txtnama.getText());
                stat.setString(3, txtalamat.getText());
                stat.setString(4, txtnohp.getText());
                stat.setString(5, (String) jekel.getSelectedItem());
                stat.setString(6, (String) kelas.getSelectedItem());
               
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
               
                txtnis.requestFocus();
              
            }   
            
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+ex);
            } 
            tabelsiswa();
            refresh();
             lebarkolong();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_txtnohpKeyPressed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
try{
         
            
         String namaFile = "src/laporan/laporan_data_siswa.jasper";
         Connection kon3 = (Connection) koneksi.connect();
             
            HashMap parameter = new HashMap();
         
            File report_file = new File(namaFile);
            JasperReport  jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter,conn);
            JasperViewer.viewReport(jasperPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }         // TODO add your handling code here:
    }//GEN-LAST:event_btncetakActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Menu.Menu a=new Menu.Menu();
a.setVisible(true);
this.dispose();


// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbaru;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jekel;
    private javax.swing.JComboBox<String> kelas;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnis;
    private javax.swing.JTextField txtnohp;
    // End of variables declaration//GEN-END:variables
}
